import os
import re

MAX_UPLOAD_BYTES = 20 * 1024 * 1024  # 20 MB -- generous for a recipe PDF/photo, bounds memory/disk use
PDF_MAGIC = b"%PDF"

# Every filename this app stores is generated by it: a short source prefix
# plus a uuid4 hex plus a validated extension (e.g. img-<32 hex>.jpg).
# Anything not matching that shape did not come from us and must never be
# joined to a directory path -- os.path.join() silently DISCARDS the base
# directory when the second argument is absolute, so an unvalidated
# "/app/data/recipes.db" would resolve to exactly that, turning an image
# field into an arbitrary-file read (via export's data-URI embedding) and
# an arbitrary-file delete (via recipe deletion's cleanup). Uploads are
# already renamed from validated content rather than client-supplied
# names; this applies the same discipline to the filename fields on the
# recipe create/update endpoints, which accept a bare string.
STORED_FILENAME_RE = re.compile(r"^[a-z]+(?:-[a-z]+)*-[0-9a-f]{32}\.(?:jpg|png|gif|webp|pdf)$")


def is_safe_stored_filename(name: str) -> bool:
    if not name or not isinstance(name, str):
        return False
    # Redundant with the regex, but stated explicitly so the intent
    # survives any future loosening of the pattern.
    if os.path.isabs(name) or os.path.basename(name) != name or ".." in name:
        return False
    return bool(STORED_FILENAME_RE.match(name))


def safe_join(base_dir: str, name: str) -> str | None:
    """Join a stored filename to a base directory, returning None if the
    name isn't one this app could have generated or if the result would
    escape base_dir. Use this instead of a bare os.path.join() anywhere a
    filename originates from request data."""
    if not is_safe_stored_filename(name):
        return None
    candidate = os.path.realpath(os.path.join(base_dir, name))
    if os.path.commonpath([os.path.realpath(base_dir), candidate]) != os.path.realpath(base_dir):
        return None
    return candidate


# Magic-byte prefix -> canonical extension. The saved filename is always
# derived from THIS, never from a client/attachment-supplied filename --
# otherwise a real image (passing the byte check) could be saved with
# e.g. a .html extension and get served back by StaticFiles with a
# browser-executable content-type (a classic polyglot stored-XSS vector).
IMAGE_MAGICS = [
    (b"\xff\xd8\xff", ".jpg"),
    (b"\x89PNG\r\n\x1a\n", ".png"),
    (b"GIF87a", ".gif"),
    (b"GIF89a", ".gif"),
    (b"RIFF", ".webp"),
]


def reencode_image(path: str):
    """Decode and re-save the image via Pillow, discarding anything in the
    file that isn't actual pixel data (EXIF payloads, trailing bytes after
    a valid image stream, other polyglot content). Passing the magic-byte
    check only proves the file *starts with* a valid image signature, not
    that the rest of the file is nothing else. Runs after that check, before
    the file is considered a finished upload.

    Uses getdata()/putdata() into a fresh Image rather than a plain
    open-then-save round trip: tested directly against a polyglot file
    (valid PNG bytes + appended non-image data) and confirmed this survives
    it, while a plain img.load(); img.save() on the same input reliably
    raises "broken data stream" and rejects an otherwise-fine upload. Don't
    simplify this without re-testing against that case.

    EXIF orientation is applied to the pixel data itself (not carried
    forward as metadata, all of which is still stripped) before the
    metadata-stripping copy -- otherwise a photo taken in portrait could
    come out sideways once EXIF is gone.

    Note: for multi-frame GIFs this keeps only the first frame -- animated
    recipe photos aren't a real use case here, so that's an accepted
    simplification, not an oversight."""
    from PIL import Image, ImageOps
    with Image.open(path) as img:
        img.load()  # force full decode now, not lazily later
        fmt = img.format  # save() can't infer format from this temp filename
        oriented = ImageOps.exif_transpose(img)  # bakes EXIF rotation into pixels
        clean = Image.new(oriented.mode, oriented.size)
        clean.putdata(list(oriented.getdata()))
        clean.save(path, format=fmt)


def validate_and_save_image_bytes(content: bytes, dest_dir: str, name_prefix: str) -> str | None:
    """Shared core for saving image bytes from any source -- user upload,
    a URL-ingested page's thumbnail, a PDF's embedded image, or an emailed
    attachment -- through the same validation pipeline: magic-byte check
    (which also determines the stored extension; never trust a source-
    provided name/extension) then Pillow re-encode to strip anything that
    isn't actual pixel data. Returns the stored filename, or None if the
    bytes don't validate as an image -- callers should treat a showcase
    image as optional and never let a failure here fail the whole
    ingestion."""
    if not content:
        return None
    first_chunk = content[:16]
    ext = next((mapped for magic, mapped in IMAGE_MAGICS if first_chunk.startswith(magic)), None)
    if ext is None:
        return None
    final_name = f"{name_prefix}{ext}"
    dest_path = os.path.join(dest_dir, final_name)
    with open(dest_path, "wb") as f:
        f.write(content)
    try:
        reencode_image(dest_path)
    except Exception:
        if os.path.isfile(dest_path):
            os.remove(dest_path)
        return None
    return final_name


def validate_and_save_pdf_bytes(content: bytes, dest_dir: str, name_prefix: str,
                                 max_bytes: int = MAX_UPLOAD_BYTES) -> str | None:
    """Bytes-based counterpart to the streaming-upload PDF path, for
    sources that already have the full content in memory (an email
    attachment, specifically) rather than an UploadFile to stream. Same
    size cap and magic-byte check as any other PDF entry point; the page
    count cap is still enforced downstream by extract_pdf_text() when the
    file is actually read. Returns the stored filename, or None if the
    bytes don't validate."""
    if not content or len(content) > max_bytes:
        return None
    if not content[:4].startswith(PDF_MAGIC):
        return None
    final_name = f"{name_prefix}.pdf"
    dest_path = os.path.join(dest_dir, final_name)
    with open(dest_path, "wb") as f:
        f.write(content)
    return final_name
